spring:
  application:
    name: AssetTrading
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://to-on.kr:3306/hanyang2
    username: to_on_admin
    password: BgCt9kuMws9jOivFj05UcEYpauecNa076H0oontnNrUGgG13lr

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  # WebSocket Configuration
  websocket:
    max-text-message-size: 8192
    max-binary-message-size: 8192

server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: ERROR
    com.example.AssetTrading: DEBUG

# 외부 API 설정
allbaro:
  api:
    url: https://api.odcloud.kr/api/nts-businessman/v1/validate
    key: BewiLghfZi%2Fmtgug%2FWSyV0S97krKzeaIPXWkRFlLE4A2FsqfCqVDri03uY4pg7XbYnhoA7fTCb7z0VCGiHX4RQ%3D%3D

# 국세청 사업자등록정보 진위확인 API 설정
business:
  api:
    url: https://api.odcloud.kr/api/nts-businessman/v1/validate
    key: BewiLghfZi%2Fmtgug%2FWSyV0S97krKzeaIPXWkRFlLE4A2FsqfCqVDri03uY4pg7XbYnhoA7fTCb7z0VCGiHX4RQ%3D%3D
